version: '3.0'

services:
  web:
    build: ./services/web
    image: web
    container_name: web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/nltk_data/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=flask_dev

  worker:
    image: web
    command: python manage.py run_worker
    volumes:
      - ./services/web/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  redis:
      image: redis:5.0.7-alpine

volumes:
  postgres_data:
